name: Jekyll site CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Jika kamu hanya menjalankan container dan bukan menarik/push image, login tidak diperlukan
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        --rm \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    
    # Login ke Docker Hub hanya untuk build/push image, jika diperlukan
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Pastikan ada Dockerfile di repositori jika kamu ingin build dan push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: cutsula/aplikasi_perpustakaan:latest
